apiVersion: v1
kind: Service
metadata:
  name: product-eloan
  labels:
    run: product-eloan
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30004
    protocol: TCP
  selector:
    app: product-eloan
  type: NodePort
